#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : geoclue
Version  : 2.5.5
Release  : 21
URL      : https://gitlab.freedesktop.org/geoclue/geoclue/-/archive/2.5.5/geoclue-2.5.5.tar.bz2
Source0  : https://gitlab.freedesktop.org/geoclue/geoclue/-/archive/2.5.5/geoclue-2.5.5.tar.bz2
Summary  : The Geoinformation Service
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: geoclue-data = %{version}-%{release}
Requires: geoclue-lib = %{version}-%{release}
Requires: geoclue-libexec = %{version}-%{release}
Requires: geoclue-license = %{version}-%{release}
Requires: geoclue-man = %{version}-%{release}
Requires: geoclue-services = %{version}-%{release}
BuildRequires : ModemManager-dev
BuildRequires : buildreq-meson
BuildRequires : desktop-file-utils
BuildRequires : gobject-introspection-dev
BuildRequires : intltool-dev
BuildRequires : libnotify-dev
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libnotify)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(systemd)
BuildRequires : vala
Patch1: 0001-Redo-stateless-patch.patch

%description
Geoclue: The Geoinformation Service
===================================
Geoclue is a D-Bus geoinformation service. The goal of the Geoclue project
is to make creating location-aware applications as simple as possible.

%package data
Summary: data components for the geoclue package.
Group: Data

%description data
data components for the geoclue package.


%package dev
Summary: dev components for the geoclue package.
Group: Development
Requires: geoclue-lib = %{version}-%{release}
Requires: geoclue-data = %{version}-%{release}
Provides: geoclue-devel = %{version}-%{release}
Requires: geoclue = %{version}-%{release}

%description dev
dev components for the geoclue package.


%package lib
Summary: lib components for the geoclue package.
Group: Libraries
Requires: geoclue-data = %{version}-%{release}
Requires: geoclue-libexec = %{version}-%{release}
Requires: geoclue-license = %{version}-%{release}

%description lib
lib components for the geoclue package.


%package libexec
Summary: libexec components for the geoclue package.
Group: Default
Requires: geoclue-license = %{version}-%{release}

%description libexec
libexec components for the geoclue package.


%package license
Summary: license components for the geoclue package.
Group: Default

%description license
license components for the geoclue package.


%package man
Summary: man components for the geoclue package.
Group: Default

%description man
man components for the geoclue package.


%package services
Summary: services components for the geoclue package.
Group: Systemd services

%description services
services components for the geoclue package.


%prep
%setup -q -n geoclue-2.5.5
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1569881061
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dgtk-doc=false \
-Dcdma-source=false \
-Dnmea-source=false \
-Ddbus-sys-dir=/usr/share/dbus-1/system.d  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/geoclue
cp COPYING %{buildroot}/usr/share/package-licenses/geoclue/COPYING
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/geoclue/COPYING.LIB
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Geoclue-2.0.typelib
/usr/share/applications/geoclue-demo-agent.desktop
/usr/share/applications/geoclue-where-am-i.desktop
/usr/share/dbus-1/interfaces/org.freedesktop.GeoClue2.Agent.xml
/usr/share/dbus-1/interfaces/org.freedesktop.GeoClue2.Client.xml
/usr/share/dbus-1/interfaces/org.freedesktop.GeoClue2.Location.xml
/usr/share/dbus-1/interfaces/org.freedesktop.GeoClue2.Manager.xml
/usr/share/dbus-1/interfaces/org.freedesktop.GeoClue2.xml
/usr/share/dbus-1/system-services/org.freedesktop.GeoClue2.service
/usr/share/dbus-1/system.d/org.freedesktop.GeoClue2.Agent.conf
/usr/share/dbus-1/system.d/org.freedesktop.GeoClue2.conf
/usr/share/defaults/etc/geoclue.conf
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/libgeoclue-2.0.deps
/usr/share/vala/vapi/libgeoclue-2.0.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/libgeoclue-2.0/gclue-client.h
/usr/include/libgeoclue-2.0/gclue-enum-types.h
/usr/include/libgeoclue-2.0/gclue-enums.h
/usr/include/libgeoclue-2.0/gclue-helpers.h
/usr/include/libgeoclue-2.0/gclue-location.h
/usr/include/libgeoclue-2.0/gclue-manager.h
/usr/include/libgeoclue-2.0/gclue-simple.h
/usr/include/libgeoclue-2.0/geoclue.h
/usr/lib64/libgeoclue-2.so
/usr/lib64/pkgconfig/geoclue-2.0.pc
/usr/lib64/pkgconfig/libgeoclue-2.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgeoclue-2.so.0
/usr/lib64/libgeoclue-2.so.0.0.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/geoclue
/usr/libexec/geoclue-2.0/demos/agent
/usr/libexec/geoclue-2.0/demos/where-am-i

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/geoclue/COPYING
/usr/share/package-licenses/geoclue/COPYING.LIB

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/geoclue.5

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/geoclue.service
